all: asobi2 asobi asobi3 asobi4 asobi5 asobi6

asobi: asobi.c
	gcc -o asobi asobi.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

asobi2: asobi2.c
	gcc -o asobi2 asobi2.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

asobi3: asobi3.c
	gcc -o asobi3 asobi3.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

asobi4: asobi4.c
	gcc -o asobi4 asobi4.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

asobi5: asobi5.c
	gcc -o asobi5 asobi5.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

asobi6: asobi6.c
	gcc -o asobi6 asobi6.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm
