all: honban honban1 honban2 honban3 honban4

honban: honban.c
	gcc -o honban honban.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

honban1: honban1.c
	gcc -o honban1 honban1.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

honban2: honban2.c
	gcc -o honban2 honban2.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

honban3: honban3.c
	gcc -o honban3 honban3.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm

honban4: honban4.c
	gcc -o honban4 honban4.c -lglut -lGLU -lGL  -lXi -lXext -lX11 -lm
